#
# DO NOT EDIT THIS FILE DIRECTLY - UNLESS YOU KNOW WHAT YOU ARE DOING
#

user node[:textgenerator][:user] do
  action :create
  supports :manage_home => true
  home "/home/#{node[:textgenerator][:user]}"
  shell "/bin/bash"
  not_if "getent passwd #{node[:textgenerator]['user']}"
end

group node[:textgenerator][:group] do
  action :modify
  members ["#{node[:textgenerator][:user]}"]
  append true
end


private_ip = my_private_ip()
public_ip = my_public_ip()



# Pre-Experiment Code


# Configuration Files


